package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Locator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/wsjdk/Corretto8Src/installers/windows/zip/corretto-build/buildRoot/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, January 18, 2024 8:57:23 PM UTC
*/

public interface Locator extends LocatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Locator
